### PR TITLE
Some Bug Fixes and Improvements

### PR DESCRIPTION
**Pull request by Jahhow**
https://youtu.be/aVJil1pHBUE
See the commit messages for details

### CODE REVIEW

**Comment by tibbi** [comment]
what does this fix? I dont really see any improvement. Right after zooming in I cannot move around and I have to wait a bit, which is actually a regression.

**Comment by Jahhow** [comment]
The wait is due to the uninterruptible animateToBound() animation which I've added for over zooming in.
Please see the commit messages for each fix and animation changes.

**Comment by tibbi** [comment]
I dont want to wait for animateToBound, it is really bad user experience. Thats why I made it instant. I cannot reproduce the "Rotation animation not centered" issue, nobody even reported it so far.

**Comment by Jahhow** [comment]
I think except of fling animation, other kind of animation are originally uninterruptible.
"Rotation animation not centered" issue may be reproduced by using landscape mode.

**Comment by tibbi** [comment]
revert that animateToBound() in all cases please, I dont want to wait after zooming in

**Comment by Jahhow** [comment]
I didn't really touch the animateToBounds() Logic which is originally there.  If you really dislike it, maybe it can be scheduled for future works.

**Comment by tibbi** [comment]
well I dont know what changed then, you mixed many things in one pull request. Just allow moving around instantly then, so we dont have to wait after zooming in.

**Comment by Jahhow** [comment]
'Double tap zoom in' originally does not allow user to move instantly. This would be nice if it can. I actually did plan to make it be able in the future.

**Comment by tibbi** [comment]
it does, you can move around right after zooming in with double tap

**Pull request closed without merging**
